# fly.toml app configuration file generated for rate-your-mentor on 2024-08-06T12:33:09+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rate-your-mentor'
primary_region = 'ams'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.3'

[env]
  APP_ENV = 'production'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  SESSION_DRIVER = 'cookie'
  SESSION_SECURE_COOKIE = 'true'
  # added these
  APP_NAME = 'RateYourMentor'
  APP_URL = 'https://rate-your-mentor.fly.dev'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[deploy]
  release_command = "php /var/www/html/artisan migrate --force && php /var/www/html/artisan up"

[[vm]]
  size = 'shared-cpu-1x'
